version: "3.9"

services:
  Nir209:
    image: nirpery/flight-project-itush:v1
    container_name: Nir209
    restart: unless-stopped

  Itamar1996:
    image: nirpery/flight-project-itush:v1
    container_name: Itamar1996
    restart: unless-stopped

  Nave2019:
    image: nirpery/flight-project-itush:v1
    container_name: Nave2019
    restart: unless-stopped

  passport-api1:
    image: nirpery/passport-api:v3
    container_name: passport-api1
    restart: unless-stopped
    expose:
      - "8000"

  passport-api2:
    image: nirpery/passport-api:v3
    container_name: passport-api2
    restart: unless-stopped
    expose:
      - "8000"
